version: '2.1'

volumes:
  speedtest_config:
# 1  dnsmasq_config:
# 2  dnscrypt_config:

services:
  speedtest:
    build: ./speedtest-cli
    privileged: true
    volumes:
      - 'speedtest_config:/etc/speedtest'
# 1     - 'influx_config:/etc/dnsmasq.d'
    dns:
      - '1.1.1.1'
      - '8.8.8.8'
    network_mode: host

  # set pihole DNS1 and DNS2 service variables to 127.0.0.1#5053 to use dnscrypt-proxy for upstream DNS
# 2  dnscrypt-proxy:
#    build: ./dnscrypt-proxy
#    volumes:
#      - 'dnscrypt_config:/config'
#    ports:
#      - '5053:5053/udp'
